#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryFromInternal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JMGJJFact")]
	public partial class LinqToJMGJJFactDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LinqToJMGJJFactDataContext() : 
				base(global::QueryFromInternal.Properties.Settings.Default.JMGJJFactConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJMGJJFactDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJMGJJFactDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJMGJJFactDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJMGJJFactDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lxb_EX_GDBS_BJ")]
		public ISingleResult<lxb_EX_GDBS_BJResult> lxb_EX_GDBS_BJ([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeginDate", DbType="DateTime")] System.Nullable<System.DateTime> beginDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), beginDate, endDate);
			return ((ISingleResult<lxb_EX_GDBS_BJResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lxb_EX_GDBS_SB")]
		public ISingleResult<lxb_EX_GDBS_SBResult> lxb_EX_GDBS_SB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeginDate", DbType="DateTime")] System.Nullable<System.DateTime> beginDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), beginDate, endDate);
			return ((ISingleResult<lxb_EX_GDBS_SBResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lxb_EX_GDBS_SL")]
		public ISingleResult<lxb_EX_GDBS_SLResult> lxb_EX_GDBS_SL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeginDate", DbType="DateTime")] System.Nullable<System.DateTime> beginDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), beginDate, endDate);
			return ((ISingleResult<lxb_EX_GDBS_SLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lxb_EX_GDBS_SPCL")]
		public ISingleResult<lxb_EX_GDBS_SPCLResult> lxb_EX_GDBS_SPCL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeginDate", DbType="DateTime")] System.Nullable<System.DateTime> beginDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), beginDate, endDate);
			return ((ISingleResult<lxb_EX_GDBS_SPCLResult>)(result.ReturnValue));
		}
	}
	
	public partial class lxb_EX_GDBS_BJResult
	{
		
		private string _S_GUID;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _BJBMMC;
		
		private string _BJBMZZJDDM;
		
		private string _XZQHDM;
		
		private string _BJJGDM;
		
		private string _BJJGMS;
		
		private string _ZFHTHYY;
		
		private string _ZJGZMC;
		
		private string _ZJBH;
		
		private string _ZJYXQX;
		
		private string _SFJE;
		
		private string _JEDWDM;
		
		private System.DateTime _BJSJ;
		
		private string _BZ;
		
		private string _BYZD;
		
		public lxb_EX_GDBS_BJResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(255)")]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this._S_GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(34)")]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this._SBLSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this._SXBM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJBMMC", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string BJBMMC
		{
			get
			{
				return this._BJBMMC;
			}
			set
			{
				if ((this._BJBMMC != value))
				{
					this._BJBMMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJBMZZJDDM", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string BJBMZZJDDM
		{
			get
			{
				return this._BJBMZZJDDM;
			}
			set
			{
				if ((this._BJBMZZJDDM != value))
				{
					this._BJBMZZJDDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this._XZQHDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJJGDM", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BJJGDM
		{
			get
			{
				return this._BJJGDM;
			}
			set
			{
				if ((this._BJJGDM != value))
				{
					this._BJJGDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJJGMS", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string BJJGMS
		{
			get
			{
				return this._BJJGMS;
			}
			set
			{
				if ((this._BJJGMS != value))
				{
					this._BJJGMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZFHTHYY", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ZFHTHYY
		{
			get
			{
				return this._ZFHTHYY;
			}
			set
			{
				if ((this._ZFHTHYY != value))
				{
					this._ZFHTHYY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJGZMC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ZJGZMC
		{
			get
			{
				return this._ZJGZMC;
			}
			set
			{
				if ((this._ZJGZMC != value))
				{
					this._ZJGZMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJBH", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ZJBH
		{
			get
			{
				return this._ZJBH;
			}
			set
			{
				if ((this._ZJBH != value))
				{
					this._ZJBH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJYXQX", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ZJYXQX
		{
			get
			{
				return this._ZJYXQX;
			}
			set
			{
				if ((this._ZJYXQX != value))
				{
					this._ZJYXQX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFJE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SFJE
		{
			get
			{
				return this._SFJE;
			}
			set
			{
				if ((this._SFJE != value))
				{
					this._SFJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JEDWDM", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string JEDWDM
		{
			get
			{
				return this._JEDWDM;
			}
			set
			{
				if ((this._JEDWDM != value))
				{
					this._JEDWDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJSJ", DbType="DateTime NOT NULL")]
		public System.DateTime BJSJ
		{
			get
			{
				return this._BJSJ;
			}
			set
			{
				if ((this._BJSJ != value))
				{
					this._BJSJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this._BZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this._BYZD = value;
				}
			}
		}
	}
	
	public partial class lxb_EX_GDBS_SBResult
	{
		
		private string _S_GUID;
		
		private string _S_STATUS;
		
		private string _OPERATETYPE;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _SXMC;
		
		private string _FSXBM;
		
		private string _FSXMC;
		
		private string _SQRLX;
		
		private string _SQRMC;
		
		private System.Nullable<int> _SQRZJLX;
		
		private string _SQRZJHM;
		
		private string _LXRXM;
		
		private System.Nullable<int> _LXRZJLX;
		
		private string _LXRSFZJHM;
		
		private string _LXRSJ;
		
		private string _LXRYX;
		
		private string _SBXMMC;
		
		private string _SBCLQD;
		
		private string _TJFS;
		
		private System.Nullable<int> _SBHZH;
		
		private System.Nullable<System.DateTime> _SBSJ;
		
		private string _SBJTWD;
		
		private string _XZQHDM;
		
		private string _YSBLSH;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
		public lxb_EX_GDBS_SBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(255)")]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this._S_GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_STATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string S_STATUS
		{
			get
			{
				return this._S_STATUS;
			}
			set
			{
				if ((this._S_STATUS != value))
				{
					this._S_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATETYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string OPERATETYPE
		{
			get
			{
				return this._OPERATETYPE;
			}
			set
			{
				if ((this._OPERATETYPE != value))
				{
					this._OPERATETYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(34)")]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this._SBLSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this._SXBM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXMC", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string SXMC
		{
			get
			{
				return this._SXMC;
			}
			set
			{
				if ((this._SXMC != value))
				{
					this._SXMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FSXBM", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string FSXBM
		{
			get
			{
				return this._FSXBM;
			}
			set
			{
				if ((this._FSXBM != value))
				{
					this._FSXBM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FSXMC", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string FSXMC
		{
			get
			{
				return this._FSXMC;
			}
			set
			{
				if ((this._FSXMC != value))
				{
					this._FSXMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRLX", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SQRLX
		{
			get
			{
				return this._SQRLX;
			}
			set
			{
				if ((this._SQRLX != value))
				{
					this._SQRLX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRMC", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string SQRMC
		{
			get
			{
				return this._SQRMC;
			}
			set
			{
				if ((this._SQRMC != value))
				{
					this._SQRMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRZJLX", DbType="Int")]
		public System.Nullable<int> SQRZJLX
		{
			get
			{
				return this._SQRZJLX;
			}
			set
			{
				if ((this._SQRZJLX != value))
				{
					this._SQRZJLX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRZJHM", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string SQRZJHM
		{
			get
			{
				return this._SQRZJHM;
			}
			set
			{
				if ((this._SQRZJHM != value))
				{
					this._SQRZJHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRXM", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string LXRXM
		{
			get
			{
				return this._LXRXM;
			}
			set
			{
				if ((this._LXRXM != value))
				{
					this._LXRXM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRZJLX", DbType="Int")]
		public System.Nullable<int> LXRZJLX
		{
			get
			{
				return this._LXRZJLX;
			}
			set
			{
				if ((this._LXRZJLX != value))
				{
					this._LXRZJLX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRSFZJHM", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string LXRSFZJHM
		{
			get
			{
				return this._LXRSFZJHM;
			}
			set
			{
				if ((this._LXRSFZJHM != value))
				{
					this._LXRSFZJHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRSJ", DbType="VarChar(55) NOT NULL", CanBeNull=false)]
		public string LXRSJ
		{
			get
			{
				return this._LXRSJ;
			}
			set
			{
				if ((this._LXRSJ != value))
				{
					this._LXRSJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRYX", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string LXRYX
		{
			get
			{
				return this._LXRYX;
			}
			set
			{
				if ((this._LXRYX != value))
				{
					this._LXRYX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBXMMC", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string SBXMMC
		{
			get
			{
				return this._SBXMMC;
			}
			set
			{
				if ((this._SBXMMC != value))
				{
					this._SBXMMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBCLQD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SBCLQD
		{
			get
			{
				return this._SBCLQD;
			}
			set
			{
				if ((this._SBCLQD != value))
				{
					this._SBCLQD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJFS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string TJFS
		{
			get
			{
				return this._TJFS;
			}
			set
			{
				if ((this._TJFS != value))
				{
					this._TJFS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBHZH", DbType="Int")]
		public System.Nullable<int> SBHZH
		{
			get
			{
				return this._SBHZH;
			}
			set
			{
				if ((this._SBHZH != value))
				{
					this._SBHZH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBSJ", DbType="DateTime")]
		public System.Nullable<System.DateTime> SBSJ
		{
			get
			{
				return this._SBSJ;
			}
			set
			{
				if ((this._SBSJ != value))
				{
					this._SBSJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBJTWD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SBJTWD
		{
			get
			{
				return this._SBJTWD;
			}
			set
			{
				if ((this._SBJTWD != value))
				{
					this._SBJTWD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this._XZQHDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YSBLSH", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string YSBLSH
		{
			get
			{
				return this._YSBLSH;
			}
			set
			{
				if ((this._YSBLSH != value))
				{
					this._YSBLSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this._BZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this._BYZD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this._ISHANDLE = value;
				}
			}
		}
	}
	
	public partial class lxb_EX_GDBS_SLResult
	{
		
		private string _S_GUID;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private int _YWLSH;
		
		private string _SLBMMC;
		
		private string _SLBMZZJDDM;
		
		private string _XZQHDM;
		
		private string _BLRXM;
		
		private string _BLRGH;
		
		private string _SLZTDM;
		
		private string _BSLYY;
		
		private string _SLHZH;
		
		private System.Nullable<System.DateTime> _SLSJ;
		
		private string _GXDXZQHDM;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
		public lxb_EX_GDBS_SLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(255)")]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this._S_GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(34)")]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this._SBLSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this._SXBM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YWLSH", DbType="Int NOT NULL")]
		public int YWLSH
		{
			get
			{
				return this._YWLSH;
			}
			set
			{
				if ((this._YWLSH != value))
				{
					this._YWLSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBMMC", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string SLBMMC
		{
			get
			{
				return this._SLBMMC;
			}
			set
			{
				if ((this._SLBMMC != value))
				{
					this._SLBMMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBMZZJDDM", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string SLBMZZJDDM
		{
			get
			{
				return this._SLBMZZJDDM;
			}
			set
			{
				if ((this._SLBMZZJDDM != value))
				{
					this._SLBMZZJDDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this._XZQHDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLRXM", DbType="VarChar(255)")]
		public string BLRXM
		{
			get
			{
				return this._BLRXM;
			}
			set
			{
				if ((this._BLRXM != value))
				{
					this._BLRXM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLRGH", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BLRGH
		{
			get
			{
				return this._BLRGH;
			}
			set
			{
				if ((this._BLRGH != value))
				{
					this._BLRGH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLZTDM", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SLZTDM
		{
			get
			{
				return this._SLZTDM;
			}
			set
			{
				if ((this._SLZTDM != value))
				{
					this._SLZTDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSLYY", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BSLYY
		{
			get
			{
				return this._BSLYY;
			}
			set
			{
				if ((this._BSLYY != value))
				{
					this._BSLYY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLHZH", DbType="VarChar(255)")]
		public string SLHZH
		{
			get
			{
				return this._SLHZH;
			}
			set
			{
				if ((this._SLHZH != value))
				{
					this._SLHZH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLSJ", DbType="DateTime")]
		public System.Nullable<System.DateTime> SLSJ
		{
			get
			{
				return this._SLSJ;
			}
			set
			{
				if ((this._SLSJ != value))
				{
					this._SLSJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GXDXZQHDM", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string GXDXZQHDM
		{
			get
			{
				return this._GXDXZQHDM;
			}
			set
			{
				if ((this._GXDXZQHDM != value))
				{
					this._GXDXZQHDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this._BZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this._BYZD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this._ISHANDLE = value;
				}
			}
		}
	}
	
	public partial class lxb_EX_GDBS_SPCLResult
	{
		
		private string _S_GUID;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _SPHJDM;
		
		private string _SPHJMC;
		
		private string _SPBMMC;
		
		private string _SPBMZZJDMD;
		
		private string _XZQHDM;
		
		private string _SPRXM;
		
		private string _SPRZWDM;
		
		private string _SPRZWMC;
		
		private string _SPYJ;
		
		private System.Nullable<System.DateTime> _SPSJ;
		
		private string _SPHJZTDM;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
		public lxb_EX_GDBS_SPCLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(255)")]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this._S_GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(34)")]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this._SBLSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this._SXBM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHJDM", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SPHJDM
		{
			get
			{
				return this._SPHJDM;
			}
			set
			{
				if ((this._SPHJDM != value))
				{
					this._SPHJDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHJMC", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string SPHJMC
		{
			get
			{
				return this._SPHJMC;
			}
			set
			{
				if ((this._SPHJMC != value))
				{
					this._SPHJMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPBMMC", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string SPBMMC
		{
			get
			{
				return this._SPBMMC;
			}
			set
			{
				if ((this._SPBMMC != value))
				{
					this._SPBMMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPBMZZJDMD", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string SPBMZZJDMD
		{
			get
			{
				return this._SPBMZZJDMD;
			}
			set
			{
				if ((this._SPBMZZJDMD != value))
				{
					this._SPBMZZJDMD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this._XZQHDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRXM", DbType="VarChar(255)")]
		public string SPRXM
		{
			get
			{
				return this._SPRXM;
			}
			set
			{
				if ((this._SPRXM != value))
				{
					this._SPRXM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRZWDM", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string SPRZWDM
		{
			get
			{
				return this._SPRZWDM;
			}
			set
			{
				if ((this._SPRZWDM != value))
				{
					this._SPRZWDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRZWMC", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string SPRZWMC
		{
			get
			{
				return this._SPRZWMC;
			}
			set
			{
				if ((this._SPRZWMC != value))
				{
					this._SPRZWMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPYJ", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string SPYJ
		{
			get
			{
				return this._SPYJ;
			}
			set
			{
				if ((this._SPYJ != value))
				{
					this._SPYJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPSJ", DbType="DateTime")]
		public System.Nullable<System.DateTime> SPSJ
		{
			get
			{
				return this._SPSJ;
			}
			set
			{
				if ((this._SPSJ != value))
				{
					this._SPSJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHJZTDM", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SPHJZTDM
		{
			get
			{
				return this._SPHJZTDM;
			}
			set
			{
				if ((this._SPHJZTDM != value))
				{
					this._SPHJZTDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this._BZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this._BYZD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this._ISHANDLE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
