#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryFromInternal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class LinqToJmwsdtDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertjmzjj_EX_GDBS_BJ(jmzjj_EX_GDBS_BJ instance);
    partial void Updatejmzjj_EX_GDBS_BJ(jmzjj_EX_GDBS_BJ instance);
    partial void Deletejmzjj_EX_GDBS_BJ(jmzjj_EX_GDBS_BJ instance);
    partial void Insertjmzjj_EX_GDBS_SB(jmzjj_EX_GDBS_SB instance);
    partial void Updatejmzjj_EX_GDBS_SB(jmzjj_EX_GDBS_SB instance);
    partial void Deletejmzjj_EX_GDBS_SB(jmzjj_EX_GDBS_SB instance);
    partial void Insertjmzjj_EX_GDBS_SL(jmzjj_EX_GDBS_SL instance);
    partial void Updatejmzjj_EX_GDBS_SL(jmzjj_EX_GDBS_SL instance);
    partial void Deletejmzjj_EX_GDBS_SL(jmzjj_EX_GDBS_SL instance);
    partial void Insertjmzjj_EX_GDBS_SPCL(jmzjj_EX_GDBS_SPCL instance);
    partial void Updatejmzjj_EX_GDBS_SPCL(jmzjj_EX_GDBS_SPCL instance);
    partial void Deletejmzjj_EX_GDBS_SPCL(jmzjj_EX_GDBS_SPCL instance);
    #endregion
		
		public LinqToJmwsdtDataContext() : 
				base(global::QueryFromInternal.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJmwsdtDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJmwsdtDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJmwsdtDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToJmwsdtDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<jmzjj_EX_GDBS_BJ> jmzjj_EX_GDBS_BJs
		{
			get
			{
				return this.GetTable<jmzjj_EX_GDBS_BJ>();
			}
		}
		
		public System.Data.Linq.Table<jmzjj_EX_GDBS_SB> jmzjj_EX_GDBS_SBs
		{
			get
			{
				return this.GetTable<jmzjj_EX_GDBS_SB>();
			}
		}
		
		public System.Data.Linq.Table<jmzjj_EX_GDBS_SL> jmzjj_EX_GDBS_SLs
		{
			get
			{
				return this.GetTable<jmzjj_EX_GDBS_SL>();
			}
		}
		
		public System.Data.Linq.Table<jmzjj_EX_GDBS_SPCL> jmzjj_EX_GDBS_SPCLs
		{
			get
			{
				return this.GetTable<jmzjj_EX_GDBS_SPCL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jmzjj_EX_GDBS_BJ")]
	public partial class jmzjj_EX_GDBS_BJ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _S_GUID;
		
		private string _S_STATUS;
		
		private string _OPERATETYPE;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _BJBMMC;
		
		private string _BJBMZZJDDM;
		
		private string _XZQHDM;
		
		private string _BJJGDM;
		
		private string _BJJGMS;
		
		private string _ZFHTHYY;
		
		private string _ZJGZMC;
		
		private string _ZJBH;
		
		private string _ZJYXQX;
		
		private string _FZGZDW;
		
		private int _SFJE;
		
		private string _JEDWDM;
		
		private System.DateTime _BJSJ;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_GUIDChanging(string value);
    partial void OnS_GUIDChanged();
    partial void OnS_STATUSChanging(string value);
    partial void OnS_STATUSChanged();
    partial void OnOPERATETYPEChanging(string value);
    partial void OnOPERATETYPEChanged();
    partial void OnSBLSHChanging(string value);
    partial void OnSBLSHChanged();
    partial void OnSXBMChanging(string value);
    partial void OnSXBMChanged();
    partial void OnBJBMMCChanging(string value);
    partial void OnBJBMMCChanged();
    partial void OnBJBMZZJDDMChanging(string value);
    partial void OnBJBMZZJDDMChanged();
    partial void OnXZQHDMChanging(string value);
    partial void OnXZQHDMChanged();
    partial void OnBJJGDMChanging(string value);
    partial void OnBJJGDMChanged();
    partial void OnBJJGMSChanging(string value);
    partial void OnBJJGMSChanged();
    partial void OnZFHTHYYChanging(string value);
    partial void OnZFHTHYYChanged();
    partial void OnZJGZMCChanging(string value);
    partial void OnZJGZMCChanged();
    partial void OnZJBHChanging(string value);
    partial void OnZJBHChanged();
    partial void OnZJYXQXChanging(string value);
    partial void OnZJYXQXChanged();
    partial void OnFZGZDWChanging(string value);
    partial void OnFZGZDWChanged();
    partial void OnSFJEChanging(int value);
    partial void OnSFJEChanged();
    partial void OnJEDWDMChanging(string value);
    partial void OnJEDWDMChanged();
    partial void OnBJSJChanging(System.DateTime value);
    partial void OnBJSJChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnBYZDChanging(string value);
    partial void OnBYZDChanged();
    partial void OnISHANDLEChanging(string value);
    partial void OnISHANDLEChanged();
    #endregion
		
		public jmzjj_EX_GDBS_BJ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this.OnS_GUIDChanging(value);
					this.SendPropertyChanging();
					this._S_GUID = value;
					this.SendPropertyChanged("S_GUID");
					this.OnS_GUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_STATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string S_STATUS
		{
			get
			{
				return this._S_STATUS;
			}
			set
			{
				if ((this._S_STATUS != value))
				{
					this.OnS_STATUSChanging(value);
					this.SendPropertyChanging();
					this._S_STATUS = value;
					this.SendPropertyChanged("S_STATUS");
					this.OnS_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATETYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string OPERATETYPE
		{
			get
			{
				return this._OPERATETYPE;
			}
			set
			{
				if ((this._OPERATETYPE != value))
				{
					this.OnOPERATETYPEChanging(value);
					this.SendPropertyChanging();
					this._OPERATETYPE = value;
					this.SendPropertyChanged("OPERATETYPE");
					this.OnOPERATETYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this.OnSBLSHChanging(value);
					this.SendPropertyChanging();
					this._SBLSH = value;
					this.SendPropertyChanged("SBLSH");
					this.OnSBLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this.OnSXBMChanging(value);
					this.SendPropertyChanging();
					this._SXBM = value;
					this.SendPropertyChanged("SXBM");
					this.OnSXBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJBMMC", DbType="VarChar(400)")]
		public string BJBMMC
		{
			get
			{
				return this._BJBMMC;
			}
			set
			{
				if ((this._BJBMMC != value))
				{
					this.OnBJBMMCChanging(value);
					this.SendPropertyChanging();
					this._BJBMMC = value;
					this.SendPropertyChanged("BJBMMC");
					this.OnBJBMMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJBMZZJDDM", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string BJBMZZJDDM
		{
			get
			{
				return this._BJBMZZJDDM;
			}
			set
			{
				if ((this._BJBMZZJDDM != value))
				{
					this.OnBJBMZZJDDMChanging(value);
					this.SendPropertyChanging();
					this._BJBMZZJDDM = value;
					this.SendPropertyChanged("BJBMZZJDDM");
					this.OnBJBMZZJDDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this.OnXZQHDMChanging(value);
					this.SendPropertyChanging();
					this._XZQHDM = value;
					this.SendPropertyChanged("XZQHDM");
					this.OnXZQHDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJJGDM", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string BJJGDM
		{
			get
			{
				return this._BJJGDM;
			}
			set
			{
				if ((this._BJJGDM != value))
				{
					this.OnBJJGDMChanging(value);
					this.SendPropertyChanging();
					this._BJJGDM = value;
					this.SendPropertyChanged("BJJGDM");
					this.OnBJJGDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJJGMS", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string BJJGMS
		{
			get
			{
				return this._BJJGMS;
			}
			set
			{
				if ((this._BJJGMS != value))
				{
					this.OnBJJGMSChanging(value);
					this.SendPropertyChanging();
					this._BJJGMS = value;
					this.SendPropertyChanged("BJJGMS");
					this.OnBJJGMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZFHTHYY", DbType="VarChar(2000)")]
		public string ZFHTHYY
		{
			get
			{
				return this._ZFHTHYY;
			}
			set
			{
				if ((this._ZFHTHYY != value))
				{
					this.OnZFHTHYYChanging(value);
					this.SendPropertyChanging();
					this._ZFHTHYY = value;
					this.SendPropertyChanged("ZFHTHYY");
					this.OnZFHTHYYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJGZMC", DbType="VarChar(1000)")]
		public string ZJGZMC
		{
			get
			{
				return this._ZJGZMC;
			}
			set
			{
				if ((this._ZJGZMC != value))
				{
					this.OnZJGZMCChanging(value);
					this.SendPropertyChanging();
					this._ZJGZMC = value;
					this.SendPropertyChanged("ZJGZMC");
					this.OnZJGZMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJBH", DbType="VarChar(1000)")]
		public string ZJBH
		{
			get
			{
				return this._ZJBH;
			}
			set
			{
				if ((this._ZJBH != value))
				{
					this.OnZJBHChanging(value);
					this.SendPropertyChanging();
					this._ZJBH = value;
					this.SendPropertyChanged("ZJBH");
					this.OnZJBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJYXQX", DbType="VarChar(1000)")]
		public string ZJYXQX
		{
			get
			{
				return this._ZJYXQX;
			}
			set
			{
				if ((this._ZJYXQX != value))
				{
					this.OnZJYXQXChanging(value);
					this.SendPropertyChanging();
					this._ZJYXQX = value;
					this.SendPropertyChanged("ZJYXQX");
					this.OnZJYXQXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FZGZDW", DbType="VarChar(1000)")]
		public string FZGZDW
		{
			get
			{
				return this._FZGZDW;
			}
			set
			{
				if ((this._FZGZDW != value))
				{
					this.OnFZGZDWChanging(value);
					this.SendPropertyChanging();
					this._FZGZDW = value;
					this.SendPropertyChanged("FZGZDW");
					this.OnFZGZDWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFJE", DbType="Int NOT NULL")]
		public int SFJE
		{
			get
			{
				return this._SFJE;
			}
			set
			{
				if ((this._SFJE != value))
				{
					this.OnSFJEChanging(value);
					this.SendPropertyChanging();
					this._SFJE = value;
					this.SendPropertyChanged("SFJE");
					this.OnSFJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JEDWDM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string JEDWDM
		{
			get
			{
				return this._JEDWDM;
			}
			set
			{
				if ((this._JEDWDM != value))
				{
					this.OnJEDWDMChanging(value);
					this.SendPropertyChanging();
					this._JEDWDM = value;
					this.SendPropertyChanged("JEDWDM");
					this.OnJEDWDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BJSJ", DbType="DateTime NOT NULL")]
		public System.DateTime BJSJ
		{
			get
			{
				return this._BJSJ;
			}
			set
			{
				if ((this._BJSJ != value))
				{
					this.OnBJSJChanging(value);
					this.SendPropertyChanging();
					this._BJSJ = value;
					this.SendPropertyChanged("BJSJ");
					this.OnBJSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(2000)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(2000)")]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this.OnBYZDChanging(value);
					this.SendPropertyChanging();
					this._BYZD = value;
					this.SendPropertyChanged("BYZD");
					this.OnBYZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this.OnISHANDLEChanging(value);
					this.SendPropertyChanging();
					this._ISHANDLE = value;
					this.SendPropertyChanged("ISHANDLE");
					this.OnISHANDLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jmzjj_EX_GDBS_SB")]
	public partial class jmzjj_EX_GDBS_SB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _S_GUID;
		
		private string _S_STATUS;
		
		private string _OPERATETYPE;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _SXMC;
		
		private string _FSXBM;
		
		private string _FSXMC;
		
		private string _SQRLX;
		
		private string _SQRMC;
		
		private string _SQRZJLX;
		
		private string _SQRZJHM;
		
		private string _LXRXM;
		
		private string _LXRZJLX;
		
		private string _LXRSFZJHM;
		
		private string _LXRSJ;
		
		private string _LXRYX;
		
		private string _SBXMMC;
		
		private string _SBCLQD;
		
		private string _TJFS;
		
		private string _SBHZH;
		
		private System.DateTime _SBSJ;
		
		private string _SBJTWD;
		
		private string _XZQHDM;
		
		private string _YSBLSH;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_GUIDChanging(string value);
    partial void OnS_GUIDChanged();
    partial void OnS_STATUSChanging(string value);
    partial void OnS_STATUSChanged();
    partial void OnOPERATETYPEChanging(string value);
    partial void OnOPERATETYPEChanged();
    partial void OnSBLSHChanging(string value);
    partial void OnSBLSHChanged();
    partial void OnSXBMChanging(string value);
    partial void OnSXBMChanged();
    partial void OnSXMCChanging(string value);
    partial void OnSXMCChanged();
    partial void OnFSXBMChanging(string value);
    partial void OnFSXBMChanged();
    partial void OnFSXMCChanging(string value);
    partial void OnFSXMCChanged();
    partial void OnSQRLXChanging(string value);
    partial void OnSQRLXChanged();
    partial void OnSQRMCChanging(string value);
    partial void OnSQRMCChanged();
    partial void OnSQRZJLXChanging(string value);
    partial void OnSQRZJLXChanged();
    partial void OnSQRZJHMChanging(string value);
    partial void OnSQRZJHMChanged();
    partial void OnLXRXMChanging(string value);
    partial void OnLXRXMChanged();
    partial void OnLXRZJLXChanging(string value);
    partial void OnLXRZJLXChanged();
    partial void OnLXRSFZJHMChanging(string value);
    partial void OnLXRSFZJHMChanged();
    partial void OnLXRSJChanging(string value);
    partial void OnLXRSJChanged();
    partial void OnLXRYXChanging(string value);
    partial void OnLXRYXChanged();
    partial void OnSBXMMCChanging(string value);
    partial void OnSBXMMCChanged();
    partial void OnSBCLQDChanging(string value);
    partial void OnSBCLQDChanged();
    partial void OnTJFSChanging(string value);
    partial void OnTJFSChanged();
    partial void OnSBHZHChanging(string value);
    partial void OnSBHZHChanged();
    partial void OnSBSJChanging(System.DateTime value);
    partial void OnSBSJChanged();
    partial void OnSBJTWDChanging(string value);
    partial void OnSBJTWDChanged();
    partial void OnXZQHDMChanging(string value);
    partial void OnXZQHDMChanged();
    partial void OnYSBLSHChanging(string value);
    partial void OnYSBLSHChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnBYZDChanging(string value);
    partial void OnBYZDChanged();
    partial void OnISHANDLEChanging(string value);
    partial void OnISHANDLEChanged();
    #endregion
		
		public jmzjj_EX_GDBS_SB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this.OnS_GUIDChanging(value);
					this.SendPropertyChanging();
					this._S_GUID = value;
					this.SendPropertyChanged("S_GUID");
					this.OnS_GUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_STATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string S_STATUS
		{
			get
			{
				return this._S_STATUS;
			}
			set
			{
				if ((this._S_STATUS != value))
				{
					this.OnS_STATUSChanging(value);
					this.SendPropertyChanging();
					this._S_STATUS = value;
					this.SendPropertyChanged("S_STATUS");
					this.OnS_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATETYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string OPERATETYPE
		{
			get
			{
				return this._OPERATETYPE;
			}
			set
			{
				if ((this._OPERATETYPE != value))
				{
					this.OnOPERATETYPEChanging(value);
					this.SendPropertyChanging();
					this._OPERATETYPE = value;
					this.SendPropertyChanged("OPERATETYPE");
					this.OnOPERATETYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this.OnSBLSHChanging(value);
					this.SendPropertyChanging();
					this._SBLSH = value;
					this.SendPropertyChanged("SBLSH");
					this.OnSBLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this.OnSXBMChanging(value);
					this.SendPropertyChanging();
					this._SXBM = value;
					this.SendPropertyChanged("SXBM");
					this.OnSXBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXMC", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string SXMC
		{
			get
			{
				return this._SXMC;
			}
			set
			{
				if ((this._SXMC != value))
				{
					this.OnSXMCChanging(value);
					this.SendPropertyChanging();
					this._SXMC = value;
					this.SendPropertyChanged("SXMC");
					this.OnSXMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FSXBM", DbType="VarChar(50)")]
		public string FSXBM
		{
			get
			{
				return this._FSXBM;
			}
			set
			{
				if ((this._FSXBM != value))
				{
					this.OnFSXBMChanging(value);
					this.SendPropertyChanging();
					this._FSXBM = value;
					this.SendPropertyChanged("FSXBM");
					this.OnFSXBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FSXMC", DbType="VarChar(1000)")]
		public string FSXMC
		{
			get
			{
				return this._FSXMC;
			}
			set
			{
				if ((this._FSXMC != value))
				{
					this.OnFSXMCChanging(value);
					this.SendPropertyChanging();
					this._FSXMC = value;
					this.SendPropertyChanged("FSXMC");
					this.OnFSXMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRLX", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string SQRLX
		{
			get
			{
				return this._SQRLX;
			}
			set
			{
				if ((this._SQRLX != value))
				{
					this.OnSQRLXChanging(value);
					this.SendPropertyChanging();
					this._SQRLX = value;
					this.SendPropertyChanged("SQRLX");
					this.OnSQRLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRMC", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string SQRMC
		{
			get
			{
				return this._SQRMC;
			}
			set
			{
				if ((this._SQRMC != value))
				{
					this.OnSQRMCChanging(value);
					this.SendPropertyChanging();
					this._SQRMC = value;
					this.SendPropertyChanged("SQRMC");
					this.OnSQRMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRZJLX", DbType="VarChar(2)")]
		public string SQRZJLX
		{
			get
			{
				return this._SQRZJLX;
			}
			set
			{
				if ((this._SQRZJLX != value))
				{
					this.OnSQRZJLXChanging(value);
					this.SendPropertyChanging();
					this._SQRZJLX = value;
					this.SendPropertyChanged("SQRZJLX");
					this.OnSQRZJLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQRZJHM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SQRZJHM
		{
			get
			{
				return this._SQRZJHM;
			}
			set
			{
				if ((this._SQRZJHM != value))
				{
					this.OnSQRZJHMChanging(value);
					this.SendPropertyChanging();
					this._SQRZJHM = value;
					this.SendPropertyChanged("SQRZJHM");
					this.OnSQRZJHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRXM", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string LXRXM
		{
			get
			{
				return this._LXRXM;
			}
			set
			{
				if ((this._LXRXM != value))
				{
					this.OnLXRXMChanging(value);
					this.SendPropertyChanging();
					this._LXRXM = value;
					this.SendPropertyChanged("LXRXM");
					this.OnLXRXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRZJLX", DbType="VarChar(2)")]
		public string LXRZJLX
		{
			get
			{
				return this._LXRZJLX;
			}
			set
			{
				if ((this._LXRZJLX != value))
				{
					this.OnLXRZJLXChanging(value);
					this.SendPropertyChanging();
					this._LXRZJLX = value;
					this.SendPropertyChanged("LXRZJLX");
					this.OnLXRZJLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRSFZJHM", DbType="VarChar(50)")]
		public string LXRSFZJHM
		{
			get
			{
				return this._LXRSFZJHM;
			}
			set
			{
				if ((this._LXRSFZJHM != value))
				{
					this.OnLXRSFZJHMChanging(value);
					this.SendPropertyChanging();
					this._LXRSFZJHM = value;
					this.SendPropertyChanged("LXRSFZJHM");
					this.OnLXRSFZJHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRSJ", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string LXRSJ
		{
			get
			{
				return this._LXRSJ;
			}
			set
			{
				if ((this._LXRSJ != value))
				{
					this.OnLXRSJChanging(value);
					this.SendPropertyChanging();
					this._LXRSJ = value;
					this.SendPropertyChanged("LXRSJ");
					this.OnLXRSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXRYX", DbType="VarChar(400)")]
		public string LXRYX
		{
			get
			{
				return this._LXRYX;
			}
			set
			{
				if ((this._LXRYX != value))
				{
					this.OnLXRYXChanging(value);
					this.SendPropertyChanging();
					this._LXRYX = value;
					this.SendPropertyChanged("LXRYX");
					this.OnLXRYXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBXMMC", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string SBXMMC
		{
			get
			{
				return this._SBXMMC;
			}
			set
			{
				if ((this._SBXMMC != value))
				{
					this.OnSBXMMCChanging(value);
					this.SendPropertyChanging();
					this._SBXMMC = value;
					this.SendPropertyChanged("SBXMMC");
					this.OnSBXMMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBCLQD", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string SBCLQD
		{
			get
			{
				return this._SBCLQD;
			}
			set
			{
				if ((this._SBCLQD != value))
				{
					this.OnSBCLQDChanging(value);
					this.SendPropertyChanging();
					this._SBCLQD = value;
					this.SendPropertyChanged("SBCLQD");
					this.OnSBCLQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJFS", DbType="VarChar(2)")]
		public string TJFS
		{
			get
			{
				return this._TJFS;
			}
			set
			{
				if ((this._TJFS != value))
				{
					this.OnTJFSChanging(value);
					this.SendPropertyChanging();
					this._TJFS = value;
					this.SendPropertyChanged("TJFS");
					this.OnTJFSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBHZH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SBHZH
		{
			get
			{
				return this._SBHZH;
			}
			set
			{
				if ((this._SBHZH != value))
				{
					this.OnSBHZHChanging(value);
					this.SendPropertyChanging();
					this._SBHZH = value;
					this.SendPropertyChanged("SBHZH");
					this.OnSBHZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBSJ", DbType="DateTime NOT NULL")]
		public System.DateTime SBSJ
		{
			get
			{
				return this._SBSJ;
			}
			set
			{
				if ((this._SBSJ != value))
				{
					this.OnSBSJChanging(value);
					this.SendPropertyChanging();
					this._SBSJ = value;
					this.SendPropertyChanged("SBSJ");
					this.OnSBSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBJTWD", DbType="VarChar(400)")]
		public string SBJTWD
		{
			get
			{
				return this._SBJTWD;
			}
			set
			{
				if ((this._SBJTWD != value))
				{
					this.OnSBJTWDChanging(value);
					this.SendPropertyChanging();
					this._SBJTWD = value;
					this.SendPropertyChanged("SBJTWD");
					this.OnSBJTWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this.OnXZQHDMChanging(value);
					this.SendPropertyChanging();
					this._XZQHDM = value;
					this.SendPropertyChanged("XZQHDM");
					this.OnXZQHDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YSBLSH", DbType="VarChar(50)")]
		public string YSBLSH
		{
			get
			{
				return this._YSBLSH;
			}
			set
			{
				if ((this._YSBLSH != value))
				{
					this.OnYSBLSHChanging(value);
					this.SendPropertyChanging();
					this._YSBLSH = value;
					this.SendPropertyChanged("YSBLSH");
					this.OnYSBLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(2000)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(2000)")]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this.OnBYZDChanging(value);
					this.SendPropertyChanging();
					this._BYZD = value;
					this.SendPropertyChanged("BYZD");
					this.OnBYZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this.OnISHANDLEChanging(value);
					this.SendPropertyChanging();
					this._ISHANDLE = value;
					this.SendPropertyChanged("ISHANDLE");
					this.OnISHANDLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jmzjj_EX_GDBS_SL")]
	public partial class jmzjj_EX_GDBS_SL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _S_GUID;
		
		private string _S_STATUS;
		
		private string _OPERATETYPE;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _YWLSH;
		
		private string _SLBMMC;
		
		private string _SLBMZZJDDM;
		
		private string _XZQHDM;
		
		private string _BLRXM;
		
		private string _BLRGH;
		
		private string _SLZTDM;
		
		private string _BSLYY;
		
		private string _SLHZH;
		
		private System.DateTime _SLSJ;
		
		private string _GXDXZQHDM;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_GUIDChanging(string value);
    partial void OnS_GUIDChanged();
    partial void OnS_STATUSChanging(string value);
    partial void OnS_STATUSChanged();
    partial void OnOPERATETYPEChanging(string value);
    partial void OnOPERATETYPEChanged();
    partial void OnSBLSHChanging(string value);
    partial void OnSBLSHChanged();
    partial void OnSXBMChanging(string value);
    partial void OnSXBMChanged();
    partial void OnYWLSHChanging(string value);
    partial void OnYWLSHChanged();
    partial void OnSLBMMCChanging(string value);
    partial void OnSLBMMCChanged();
    partial void OnSLBMZZJDDMChanging(string value);
    partial void OnSLBMZZJDDMChanged();
    partial void OnXZQHDMChanging(string value);
    partial void OnXZQHDMChanged();
    partial void OnBLRXMChanging(string value);
    partial void OnBLRXMChanged();
    partial void OnBLRGHChanging(string value);
    partial void OnBLRGHChanged();
    partial void OnSLZTDMChanging(string value);
    partial void OnSLZTDMChanged();
    partial void OnBSLYYChanging(string value);
    partial void OnBSLYYChanged();
    partial void OnSLHZHChanging(string value);
    partial void OnSLHZHChanged();
    partial void OnSLSJChanging(System.DateTime value);
    partial void OnSLSJChanged();
    partial void OnGXDXZQHDMChanging(string value);
    partial void OnGXDXZQHDMChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnBYZDChanging(string value);
    partial void OnBYZDChanged();
    partial void OnISHANDLEChanging(string value);
    partial void OnISHANDLEChanged();
    #endregion
		
		public jmzjj_EX_GDBS_SL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this.OnS_GUIDChanging(value);
					this.SendPropertyChanging();
					this._S_GUID = value;
					this.SendPropertyChanged("S_GUID");
					this.OnS_GUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_STATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string S_STATUS
		{
			get
			{
				return this._S_STATUS;
			}
			set
			{
				if ((this._S_STATUS != value))
				{
					this.OnS_STATUSChanging(value);
					this.SendPropertyChanging();
					this._S_STATUS = value;
					this.SendPropertyChanged("S_STATUS");
					this.OnS_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATETYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string OPERATETYPE
		{
			get
			{
				return this._OPERATETYPE;
			}
			set
			{
				if ((this._OPERATETYPE != value))
				{
					this.OnOPERATETYPEChanging(value);
					this.SendPropertyChanging();
					this._OPERATETYPE = value;
					this.SendPropertyChanged("OPERATETYPE");
					this.OnOPERATETYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this.OnSBLSHChanging(value);
					this.SendPropertyChanging();
					this._SBLSH = value;
					this.SendPropertyChanged("SBLSH");
					this.OnSBLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this.OnSXBMChanging(value);
					this.SendPropertyChanging();
					this._SXBM = value;
					this.SendPropertyChanged("SXBM");
					this.OnSXBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YWLSH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string YWLSH
		{
			get
			{
				return this._YWLSH;
			}
			set
			{
				if ((this._YWLSH != value))
				{
					this.OnYWLSHChanging(value);
					this.SendPropertyChanging();
					this._YWLSH = value;
					this.SendPropertyChanged("YWLSH");
					this.OnYWLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBMMC", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string SLBMMC
		{
			get
			{
				return this._SLBMMC;
			}
			set
			{
				if ((this._SLBMMC != value))
				{
					this.OnSLBMMCChanging(value);
					this.SendPropertyChanging();
					this._SLBMMC = value;
					this.SendPropertyChanged("SLBMMC");
					this.OnSLBMMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBMZZJDDM", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string SLBMZZJDDM
		{
			get
			{
				return this._SLBMZZJDDM;
			}
			set
			{
				if ((this._SLBMZZJDDM != value))
				{
					this.OnSLBMZZJDDMChanging(value);
					this.SendPropertyChanging();
					this._SLBMZZJDDM = value;
					this.SendPropertyChanged("SLBMZZJDDM");
					this.OnSLBMZZJDDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this.OnXZQHDMChanging(value);
					this.SendPropertyChanging();
					this._XZQHDM = value;
					this.SendPropertyChanged("XZQHDM");
					this.OnXZQHDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLRXM", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string BLRXM
		{
			get
			{
				return this._BLRXM;
			}
			set
			{
				if ((this._BLRXM != value))
				{
					this.OnBLRXMChanging(value);
					this.SendPropertyChanging();
					this._BLRXM = value;
					this.SendPropertyChanged("BLRXM");
					this.OnBLRXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLRGH", DbType="VarChar(20)")]
		public string BLRGH
		{
			get
			{
				return this._BLRGH;
			}
			set
			{
				if ((this._BLRGH != value))
				{
					this.OnBLRGHChanging(value);
					this.SendPropertyChanging();
					this._BLRGH = value;
					this.SendPropertyChanged("BLRGH");
					this.OnBLRGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLZTDM", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string SLZTDM
		{
			get
			{
				return this._SLZTDM;
			}
			set
			{
				if ((this._SLZTDM != value))
				{
					this.OnSLZTDMChanging(value);
					this.SendPropertyChanging();
					this._SLZTDM = value;
					this.SendPropertyChanged("SLZTDM");
					this.OnSLZTDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSLYY", DbType="VarChar(2000)")]
		public string BSLYY
		{
			get
			{
				return this._BSLYY;
			}
			set
			{
				if ((this._BSLYY != value))
				{
					this.OnBSLYYChanging(value);
					this.SendPropertyChanging();
					this._BSLYY = value;
					this.SendPropertyChanged("BSLYY");
					this.OnBSLYYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLHZH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SLHZH
		{
			get
			{
				return this._SLHZH;
			}
			set
			{
				if ((this._SLHZH != value))
				{
					this.OnSLHZHChanging(value);
					this.SendPropertyChanging();
					this._SLHZH = value;
					this.SendPropertyChanged("SLHZH");
					this.OnSLHZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLSJ", DbType="DateTime NOT NULL")]
		public System.DateTime SLSJ
		{
			get
			{
				return this._SLSJ;
			}
			set
			{
				if ((this._SLSJ != value))
				{
					this.OnSLSJChanging(value);
					this.SendPropertyChanging();
					this._SLSJ = value;
					this.SendPropertyChanged("SLSJ");
					this.OnSLSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GXDXZQHDM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GXDXZQHDM
		{
			get
			{
				return this._GXDXZQHDM;
			}
			set
			{
				if ((this._GXDXZQHDM != value))
				{
					this.OnGXDXZQHDMChanging(value);
					this.SendPropertyChanging();
					this._GXDXZQHDM = value;
					this.SendPropertyChanged("GXDXZQHDM");
					this.OnGXDXZQHDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(2000)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(2000)")]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this.OnBYZDChanging(value);
					this.SendPropertyChanging();
					this._BYZD = value;
					this.SendPropertyChanged("BYZD");
					this.OnBYZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this.OnISHANDLEChanging(value);
					this.SendPropertyChanging();
					this._ISHANDLE = value;
					this.SendPropertyChanged("ISHANDLE");
					this.OnISHANDLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jmzjj_EX_GDBS_SPCL")]
	public partial class jmzjj_EX_GDBS_SPCL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _S_GUID;
		
		private string _S_STATUS;
		
		private string _OPERATETYPE;
		
		private string _SBLSH;
		
		private string _SXBM;
		
		private string _SPHJDM;
		
		private string _SPHJMC;
		
		private string _SPBMMC;
		
		private string _SPBMZZJDMD;
		
		private string _XZQHDM;
		
		private string _SPRXM;
		
		private string _SPRZWDM;
		
		private string _SPRZWMC;
		
		private string _SPYJ;
		
		private System.DateTime _SPSJ;
		
		private string _SPHJZTDM;
		
		private string _BZ;
		
		private string _BYZD;
		
		private string _ISHANDLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_GUIDChanging(string value);
    partial void OnS_GUIDChanged();
    partial void OnS_STATUSChanging(string value);
    partial void OnS_STATUSChanged();
    partial void OnOPERATETYPEChanging(string value);
    partial void OnOPERATETYPEChanged();
    partial void OnSBLSHChanging(string value);
    partial void OnSBLSHChanged();
    partial void OnSXBMChanging(string value);
    partial void OnSXBMChanged();
    partial void OnSPHJDMChanging(string value);
    partial void OnSPHJDMChanged();
    partial void OnSPHJMCChanging(string value);
    partial void OnSPHJMCChanged();
    partial void OnSPBMMCChanging(string value);
    partial void OnSPBMMCChanged();
    partial void OnSPBMZZJDMDChanging(string value);
    partial void OnSPBMZZJDMDChanged();
    partial void OnXZQHDMChanging(string value);
    partial void OnXZQHDMChanged();
    partial void OnSPRXMChanging(string value);
    partial void OnSPRXMChanged();
    partial void OnSPRZWDMChanging(string value);
    partial void OnSPRZWDMChanged();
    partial void OnSPRZWMCChanging(string value);
    partial void OnSPRZWMCChanged();
    partial void OnSPYJChanging(string value);
    partial void OnSPYJChanged();
    partial void OnSPSJChanging(System.DateTime value);
    partial void OnSPSJChanged();
    partial void OnSPHJZTDMChanging(string value);
    partial void OnSPHJZTDMChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnBYZDChanging(string value);
    partial void OnBYZDChanged();
    partial void OnISHANDLEChanging(string value);
    partial void OnISHANDLEChanged();
    #endregion
		
		public jmzjj_EX_GDBS_SPCL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string S_GUID
		{
			get
			{
				return this._S_GUID;
			}
			set
			{
				if ((this._S_GUID != value))
				{
					this.OnS_GUIDChanging(value);
					this.SendPropertyChanging();
					this._S_GUID = value;
					this.SendPropertyChanged("S_GUID");
					this.OnS_GUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_STATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string S_STATUS
		{
			get
			{
				return this._S_STATUS;
			}
			set
			{
				if ((this._S_STATUS != value))
				{
					this.OnS_STATUSChanging(value);
					this.SendPropertyChanging();
					this._S_STATUS = value;
					this.SendPropertyChanged("S_STATUS");
					this.OnS_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATETYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string OPERATETYPE
		{
			get
			{
				return this._OPERATETYPE;
			}
			set
			{
				if ((this._OPERATETYPE != value))
				{
					this.OnOPERATETYPEChanging(value);
					this.SendPropertyChanging();
					this._OPERATETYPE = value;
					this.SendPropertyChanged("OPERATETYPE");
					this.OnOPERATETYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBLSH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SBLSH
		{
			get
			{
				return this._SBLSH;
			}
			set
			{
				if ((this._SBLSH != value))
				{
					this.OnSBLSHChanging(value);
					this.SendPropertyChanging();
					this._SBLSH = value;
					this.SendPropertyChanged("SBLSH");
					this.OnSBLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SXBM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SXBM
		{
			get
			{
				return this._SXBM;
			}
			set
			{
				if ((this._SXBM != value))
				{
					this.OnSXBMChanging(value);
					this.SendPropertyChanging();
					this._SXBM = value;
					this.SendPropertyChanged("SXBM");
					this.OnSXBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHJDM", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string SPHJDM
		{
			get
			{
				return this._SPHJDM;
			}
			set
			{
				if ((this._SPHJDM != value))
				{
					this.OnSPHJDMChanging(value);
					this.SendPropertyChanging();
					this._SPHJDM = value;
					this.SendPropertyChanged("SPHJDM");
					this.OnSPHJDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHJMC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SPHJMC
		{
			get
			{
				return this._SPHJMC;
			}
			set
			{
				if ((this._SPHJMC != value))
				{
					this.OnSPHJMCChanging(value);
					this.SendPropertyChanging();
					this._SPHJMC = value;
					this.SendPropertyChanged("SPHJMC");
					this.OnSPHJMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPBMMC", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string SPBMMC
		{
			get
			{
				return this._SPBMMC;
			}
			set
			{
				if ((this._SPBMMC != value))
				{
					this.OnSPBMMCChanging(value);
					this.SendPropertyChanging();
					this._SPBMMC = value;
					this.SendPropertyChanged("SPBMMC");
					this.OnSPBMMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPBMZZJDMD", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string SPBMZZJDMD
		{
			get
			{
				return this._SPBMZZJDMD;
			}
			set
			{
				if ((this._SPBMZZJDMD != value))
				{
					this.OnSPBMZZJDMDChanging(value);
					this.SendPropertyChanging();
					this._SPBMZZJDMD = value;
					this.SendPropertyChanged("SPBMZZJDMD");
					this.OnSPBMZZJDMDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XZQHDM", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string XZQHDM
		{
			get
			{
				return this._XZQHDM;
			}
			set
			{
				if ((this._XZQHDM != value))
				{
					this.OnXZQHDMChanging(value);
					this.SendPropertyChanging();
					this._XZQHDM = value;
					this.SendPropertyChanged("XZQHDM");
					this.OnXZQHDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRXM", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SPRXM
		{
			get
			{
				return this._SPRXM;
			}
			set
			{
				if ((this._SPRXM != value))
				{
					this.OnSPRXMChanging(value);
					this.SendPropertyChanging();
					this._SPRXM = value;
					this.SendPropertyChanged("SPRXM");
					this.OnSPRXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRZWDM", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string SPRZWDM
		{
			get
			{
				return this._SPRZWDM;
			}
			set
			{
				if ((this._SPRZWDM != value))
				{
					this.OnSPRZWDMChanging(value);
					this.SendPropertyChanging();
					this._SPRZWDM = value;
					this.SendPropertyChanged("SPRZWDM");
					this.OnSPRZWDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRZWMC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SPRZWMC
		{
			get
			{
				return this._SPRZWMC;
			}
			set
			{
				if ((this._SPRZWMC != value))
				{
					this.OnSPRZWMCChanging(value);
					this.SendPropertyChanging();
					this._SPRZWMC = value;
					this.SendPropertyChanged("SPRZWMC");
					this.OnSPRZWMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPYJ", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string SPYJ
		{
			get
			{
				return this._SPYJ;
			}
			set
			{
				if ((this._SPYJ != value))
				{
					this.OnSPYJChanging(value);
					this.SendPropertyChanging();
					this._SPYJ = value;
					this.SendPropertyChanged("SPYJ");
					this.OnSPYJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPSJ", DbType="DateTime NOT NULL")]
		public System.DateTime SPSJ
		{
			get
			{
				return this._SPSJ;
			}
			set
			{
				if ((this._SPSJ != value))
				{
					this.OnSPSJChanging(value);
					this.SendPropertyChanging();
					this._SPSJ = value;
					this.SendPropertyChanged("SPSJ");
					this.OnSPSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHJZTDM", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string SPHJZTDM
		{
			get
			{
				return this._SPHJZTDM;
			}
			set
			{
				if ((this._SPHJZTDM != value))
				{
					this.OnSPHJZTDMChanging(value);
					this.SendPropertyChanging();
					this._SPHJZTDM = value;
					this.SendPropertyChanged("SPHJZTDM");
					this.OnSPHJZTDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(2000)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BYZD", DbType="VarChar(2000)")]
		public string BYZD
		{
			get
			{
				return this._BYZD;
			}
			set
			{
				if ((this._BYZD != value))
				{
					this.OnBYZDChanging(value);
					this.SendPropertyChanging();
					this._BYZD = value;
					this.SendPropertyChanged("BYZD");
					this.OnBYZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHANDLE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ISHANDLE
		{
			get
			{
				return this._ISHANDLE;
			}
			set
			{
				if ((this._ISHANDLE != value))
				{
					this.OnISHANDLEChanging(value);
					this.SendPropertyChanging();
					this._ISHANDLE = value;
					this.SendPropertyChanged("ISHANDLE");
					this.OnISHANDLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
